# Generated by Django 5.0.6 on 2024-07-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0003_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='name',
        ),
    ]
