# Generated by Django 5.0.6 on 2024-07-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0004_rename_genre_name_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
