# Generated by Django 5.0.6 on 2024-07-02 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0005_alter_genre_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('rating', models.FloatField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='Poster/%Y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmapp.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmapp.movie')),
            ],
        ),
    ]
