# Generated by Django 5.0.6 on 2024-07-02 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0007_movie_active_movie_created_date_movie_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='active',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='updated_date',
        ),
    ]
