# Generated by Django 5.0.6 on 2024-07-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0009_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviegenre',
            unique_together={('movie', 'genre')},
        ),
    ]
